# Generated by Django 3.0.7 on 2020-08-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='designatio',
            new_name='designation',
        ),
    ]
