# Generated by Django 3.0.7 on 2020-08-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_to_cart',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='add_to_cart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='confirm',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='add_to_cart',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
